#! /bin/bash

$HOME/.config/polybar/launch.sh
sleep 0.5
pgrep -x sxhkd > /dev/null || sxhkd &
xset led 3
xset r rate 200 50
xsetroot -cursor_name left_ptr
nitrogen --restore &

bspc monitor -d I II III IV

bspc config normal_border_color "#aa88aa"
bspc config focused_border_color "#ffeeff"
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config border_radius 0
bspc config border_width 2
bspc config window_gap 5
bspc config padding 0
bspc config split_ratio 0.5
bspc config focus_follows_pointer false
bspc config borderless_monocle false
bspc config single_monocle false
bspc config gapless_monocle false
bspc config automatic_scheme spiral

bspc rule -a firefox state=tiled
bspc rule -a org.telegram.desktop state=tiled
bspc rule -a com.discordapp.Discord state=tiled
bspc rule -a io.github.Soundux state=tiled
bspc rule -a code state=tiled
bspc rule -a nautilus state=floating center=true
bspc rule -a nomacs state=tiled
bspc rule -a mpv state=tiled
feh --bg-fill &
