#! /bin/bash

sh /home/gnkz/.config/polybar/launch.sh
sleep 0.5
pgrep -x sxhkd > /dev/null || sxhkd &
xset led 3
xset r rate 200 50
nmcli radio wifi on
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV

bspc config normal_border_color "#aa88aa"
bspc config focused_border_color "#ffeeff"
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config border_radius 0
bspc config border_width 3
bspc config window_gap 7
bspc config padding 0
bspc config split_ratio 0.6
bspc config focus_follows_pointer false
bspc config borderless_monocle false
bspc config single_monocle false
bspc config gapless_monocle false
bspc config automatic_scheme spiral

feh --bg-fill david.jpg &