#! /bin/bash

sh /home/gnkz/.config/polybar/launch.sh
sleep 0.5
pgrep -x sxhkd > /dev/null || sxhkd &
xset r rate 200 50
nmcli radio wifi on
xsetroot -cursor_name left_ptr

INTERNAL_MONITOR="HDMI-2" #eDP-1
bspc monitor $INTERNAL_MONITOR -d I II III IV
# EXTERNAL_MONITOR="HDMI-1"
# if [[ "$1" = 0 ]]; then
# 	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
#     bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
#   fi
# fi

bspc config normal_border_color "#aa88aa"
bspc config focused_border_color "#ffeeff"
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config border_width 3
bspc config window_gap 7
bspc config padding 0
bspc config split_ratio 0.55
bspc config focus_follows_pointer false
bspc config automatic_scheme alternate

bspc rule -a kitty state=floating rectangle=400x250+1490+800 #edit by monitor (laptop 1104+740)
bspc rule -a Zathura state=tiled

feh --bg-fill void.png &