alias x='startx'
alias ls='ls -a --color=auto'
alias fzf='fzf -i --preview="cat {}" --prompt=">" --pointer="▬"'
alias cz='cd "./$(find -type d | fzf)"'
alias pin='sudo pacman -S --noconfirm'
alias yin='yay -S --noconfirm'
alias pun='sudo pacman -Rs --noconfirm'
alias yun='yay -Rs --noconfirm'
alias upd='yay -Syu --noconfirm && yay -Sc --noconfirm && paccache -r && yay -Qdtq | yay -Rns - && sudo rm -rf ~/.cache/ && sudo rm ~/Pictures/screenshots/*'
alias gi='git init'
alias gs='git status --short'
alias ga='git add --all'
alias gb='git branch -M main'
alias gpush='git push origin'
alias gpull='git pull origin'
alias gacp='git add --all && git commit -m "c" && git push origin'
alias bnp='brightness_up() { sudo brightnessctl -e -d intel_backlight set +"$1"%; }; brightness_up'
alias bnm='brightness_down() { sudo brightnessctl -e -d intel_backlight set "$1"%-; }; brightness_down'
alias meteo='weather() { curl wttr.in/"$1"?format="%l:+%t\n" ;}; weather'
alias img='kitty +kitten icat'
alias py='python3 -B'
