vim.cmd("filetype plugin indent on")
vim.cmd("syntax enable")
vim.cmd("set number")
vim.cmd("set ruler")
vim.cmd("set relativenumber")
vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set softtabstop=4")