shadow = false;
shadow-ignore-shaped = false;
fading = false;
inactive-dim-fixed = false;
corner-radius = 0;
blur-background = false;
backend = "glx";
dithered-present = false;
vsync = false;
detect-client-opacity = true;
use-damage = true;
max-brightness = 1.0;
mark-ovredir-focused = true;
