#! /bin/bash

$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &

xset led 3
xset r rate 200 50
xsetroot -cursor_name left_ptr

bspc monitor -d I II III

bspc config normal_border_color "#000000"
bspc config focused_border_color "#474554"
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config border_radius 0
bspc config border_width 2
bspc config window_gap 5
bspc config padding 0
bspc config split_ratio 0.5
bspc config focus_follows_pointer false
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config automatic_scheme spiral

bspc rule -a firefox state=fullscreen
bspc rule -a org.telegram.desktop state=fullscreen
bspc rule -a com.discordapp.Discord state=fullscreen
bspc rule -a io.github.Soundux state=fullscreen
bspc rule -a code state=fullscreen
bspc rule -a nautilus state=floating center=true
bspc rule -a nomacs state=fullscreen
bspc rule -a mpv state=fullscreen
bspc rule -a shotcut state=fullscreen
bspc rule -a gpick state=floating