#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II

bspc config normal_border_color "#e5e9f0"
bspc config active_border_color "#ffcc33"
bspc config focused_border_color "#2492e0"
bspc config presel_feedback_color "#b48ead"
bspc config urgent_border_color "#ff4040"

bspc config border_radius 0
bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config split_ratio 0.52
bspc config focus_follows_pointer true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config automatic_scheme spiral

bspc rule -a firefox state=fullscreen
bspc rule -a org.telegram.desktop state=fullscreen
bspc rule -a com.discordapp.Discord state=fullscreen
bspc rule -a io.github.Soundux state=fullscreen
bspc rule -a code state=fullscreen
bspc rule -a nautilus state=floating
bspc rule -a nomacs state=fullscreen
bspc rule -a mpv state=fullscreen
bspc rule -a shotcut state=fullscreen
bspc rule -a gpick state=floating
bspc rule -a kitty state=floating
bspc rule -a spotify state=fullscreen
# follow=on
# manage=off

# #polybar hidden when fullscreen for vlc, youtube, mpv ...
# #find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)