general {
    ignore_empty_inputs = true
    hide_cursor = true
}

animation {
    enabled = false
}

background {
    blur_passes = 3
    blur_size = 3
    path = screenshot
}

input-field {
    outline_thickness = 3
    valign = center
    dots_size = 0.1
    halign = center
    font_family = Iosevka NFM
    dots_spacing = 0.3
    fail_text = wrong password
    size = 100, 50
    placeholder_text = 
    rounding = 5
    font_color = rgba(171917FF)
    dots_center = true
    inner_color = rgba(FFFCFFFF)
    fail_color = rgba(EEB00BFF)
    outer_color = rgba(FF6D6DFF)
}

label {
    color = rgba(FFFCFFFF)
    font_family = Iosevka NFM
    position = 0, 50
    text = $TIME
    font_size = 24
}